import type { Alignment, ColumnConfig } from "./tableBuilder.js"

/** Shared minimum column widths (characters) for React tail tables. */
export const W = {
  order: 2,
  on: 2,
  own: 3,
  flag: 3,
  pick: 4,
  work: 4,
  job: 5,
  sym: 5,
  tier: 6,
  mode: 6,
  rep: 6,
  num: 7,
  rating: 7,
  morale: 7,
  energy: 7,
  price: 8,
  staff: 8,
  stored: 8,
  ms: 8,
  eta: 8,
  success: 7,
  money: 10,
  rate: 10,
  karma: 10,
  faction: 12,
  city: 12,
  division: 10,
  server: 14,
  crime: 14,
  company: 14,
  augment: 16,
  host: 16,
  field: 10,
  signal: 14,
  timeAt: 18,
  position: 22,
  why: 24,
  notes: 36,
  stat: 5,
  material: 10,
  product: 10,
  jobs: 22,
  xp: 8,
  file: 18,
  reward: 24,
  status: 8,
  jobLong: 18,
  note: 16,
  augmentName: 18,
  location: 28,
  detail: 24,
  step: 28,
  actMin: 10,
  model: 11,
  diff: 4,
  ok: 4,
  fails: 6,
  predicted: 12,
  actual: 12,
  delta: 10,
  errPct: 8,
  stage: 10,
  role: 3,
  mgmt: 4,
  gross: 8,
  pay: 8,
  est: 8,
  pctLoop: 8,
  timing: 8,
  progress: 9,
  sell: 14,
  qual: 5,
  whUsed: 9,
  useRate: 8,
  result: 6,
  lvls: 4,
  sec: 3,
  gss: 3,
  ses: 3,
  cha: 3,
  len: 3,
  dCol: 3,
  pl: 12,
  notesWide: 48,
} as const

export function col(header: string, align: Alignment, minWidth?: number): ColumnConfig {
  return minWidth != null ? { header, align, minWidth } : { header, align }
}
